seed: 123
data: {name: cifar10, root: ./data, batch_size: 128, num_workers: 4, augment: true}
model: {name: resnet18_cifar, num_classes: 10}
train: {epochs: 1, lr: 0.1, weight_decay: 5e-4}
sampler: {name: sgld, step_size: 1e-3, burn_in: 0, thin: 1, noise_scale: 1.0, num_samples: 50}
out: {dir: runs/exp1}
