# Configuration for CIFAR-10 ResNet-18 SGLD Experiment

data:
  name: cifar10
  root: data/cifar-10-batches-py
  batch_size: 128
  num_workers: 4

model:
  name: resnet18_cifar
  num_classes: 10

train:
  epochs: 0  # No pretraining, start sampling directly
  learning_rate: 1e-3
  weight_decay: 1e-4
  optimizer: sgd
  scheduler: cosine

sampler:
  type: sgld
  step_size: 1e-4
  temperature: 1.0
  burn_in: 2000
  thin: 200
  num_samples: 100
  noise_scale: 1.0

out:
  dir: runs/c10_r18_sgld
  save_samples: true
  save_traces: true
