# configs/cifar100_wrn2810_sgld.yaml
seed: 123

data:
  name: cifar100
  root: ./data
  batch_size: 128
  num_workers: 4
  augment: true

model:
  name: wrn_28_10_cifar
  num_classes: 100

train:
  epochs: 0          # no pretrain before sampling
  lr: 0.1
  weight_decay: 5e-4

sampler:
  name: sgld
  step_size: 5.0e-6      # eps0 = 0.25 / 50000
  tau: 1.0e-5
  prior_prec: 50.0

  # run control
  num_samples: 16
  burn_in: 160
  thin: 1000
  num_epochs: 300        # used to compute total steps

  # optional step-size decay (exponential)
  decay_interval: 90     # epochs
  gamma: 0.1             # multiply step_size every decay_interval epochs

  cosine_eps: true
  t_max: 300

out:
  dir: runs/c100_wrn2810_sgld