# MRPC Paraphrase Detection with DistilBERT + LoRA + ASGLD
# Microsoft Research Paraphrase Corpus - Binary classification

seed: 123

data:
  name: mrpc
  batch_size: 32
  max_length: 128
  num_workers: 4

model:
  name: distilbert-base-uncased
  lora:
    rank: 4
    alpha: 16.0
    dropout: 0.1

sampler:
  name: asgld
  step_size: 5.0e-4
  tau: 1.0
  momentum: 0.9
  burn_in: 1000
  thin: 200
  num_samples: 20
  prior_prec: 1e-4

out:
  dir: runs/experiment_mrpc_distilbert_asgld
