# SST-2 Sentiment Analysis with BERT + LoRA + SGLD
# Stanford Sentiment Treebank v2 - Binary classification

seed: 123

data:
  name: sst2
  batch_size: 32
  max_length: 128
  num_workers: 4

model:
  name: bert-base-uncased
  lora:
    rank: 8
    alpha: 16.0
    dropout: 0.1

sampler:
  name: sgld
  step_size: 5.0e-4
  tau: 1.0
  burn_in: 1000
  thin: 200
  num_samples: 20
  prior_prec: 1e-4
  
  # Cosine annealing
  cosine_eps: true
  t_max: 10000

# Evaluation during sampling (optional)
eval_during_sampling: false

out:
  dir: runs/experiment_sst2_bert_sgld
