# IMDB Sentiment Analysis with BERT + LoRA + SAM-SGLD-R1
# IMDB Movie Reviews - Binary classification

seed: 123

data:
  name: imdb
  batch_size: 32
  max_length: 256
  num_workers: 4

model:
  name: bert-base-uncased
  lora:
    rank: 16
    alpha: 16.0
    dropout: 0.1

sampler:
  name: sam_sgld_r1
  step_size: 5.0e-4
  tau: 1.0
  rho: 0.1
  burn_in: 1000
  thin: 200
  num_samples: 20
  prior_prec: 1e-4

out:
  dir: runs/experiment_imdb_bert_sam_sgld_r1
