# Base Configuration for SST-2 BERT LoRA Sampler Comparison
# Stanford Sentiment Treebank v2 - Binary classification

seed: 123

data:
  name: sst2
  batch_size: 32
  max_length: 128
  num_workers: 4

model:
  name: bert-base-uncased
  lora:
    rank: 8
    alpha: 16.0
    dropout: 0.1

sampler:
  # Base sampler configuration - override in specific experiments
  name: sgld
  step_size: 5.0e-4
  tau: 1.0
  burn_in: 1000
  thin: 200
  num_samples: 20
  prior_prec: 1e-4

out:
  dir: runs/experiment_comparison_sst2_bert
