# SST-2 Sentiment Analysis with RoBERTa + LoRA + SAM-SGLD
# Stanford Sentiment Treebank v2 - Binary classification

seed: 123

data:
  name: sst2
  batch_size: 32
  max_length: 128
  num_workers: 4

model:
  name: roberta-base
  lora:
    rank: 8
    alpha: 16.0
    dropout: 0.1

sampler:
  name: sam_sgld
  step_size: 5.0e-4
  tau: 1.0
  rho: 0.1
  burn_in: 1000
  thin: 200
  num_samples: 20
  prior_prec: 1e-4

out:
  dir: runs/experiment_sst2_roberta_sam_sgld
