# Configuration for MRPC RoBERTa LoRA SGLD Experiment
# Based on experiment outline in sgld_lora_experiment.md

experiment:
  name: "mrpc_roberta_lora_sgld"
  description: "SGLD for Bayesian LoRA on MRPC dataset"
  
model:
  backbone: "roberta-base"
  max_sequence_length: 256
  lora:
    inject_into: ["query", "key", "value", "attention.output.dense"]  # Only attention modules
    rank: 8  # Increased for better expressiveness
    alpha: 16  # Increased proportionally with rank
    dropout: 0.1

data:
  dataset: "mrpc"
  batch_size: 32  # Optimized for best convergence and GPU utilization
  gradient_accumulation_steps: 1  # No longer needed with larger batch size
  max_epochs: 20

training:
  map_lora:
    optimizer: "adamw"  # JUSTIFIED: AdamW achieves 82% vs SGD's 68% MAP accuracy
    learning_rate: 2e-4  # Standard Adam learning rate
    weight_decay: 0.01
    beta1: 0.9  # Adam momentum decay
    beta2: 0.999  # Adam squared gradient decay
    eps: 1e-8  # Adam epsilon for numerical stability
    scheduler: "none"  # Disable scheduler to avoid LR decay
    warmup_ratio: 0.0  # Disable warmup
  
  sgld_lora:
    learning_rate: 3.2e-3  # Increased step size to match effective step per sample of working version
    temperature: 2.0  # Optimized for perfect noise-gradient balance
    prior_std: 9.5  # Optimal prior for balanced SGLD sampling (experimentally determined)
    step_size_schedule:
      initial: 3.2e-3  # Increased step size to match effective step per sample of working version
      decay_rate: 0.3  # Conservative decay for better convergence
      decay_steps: 4000  # Longer decay schedule
    gradient_clip_norm: 5.0  # Match MAP training for consistency
    noise_scale: 0.001  # Increased noise scale for better parameter space exploration
    chains: 4  # Restored for R-hat computation
    burn_in_steps: 8000  # Sufficient burn-in for convergence
    sampling_steps: 3000  # 60 samples per chain * 50 thinning = 3000 steps
    thinning: 50  # Good thinning for sample independence
    samples_to_retain: 60  # Match total samples (4 chains * 60 samples per chain)

evaluation:
  metrics: ["accuracy", "nll", "ece"]
  mcmc_diagnostics:
    probe_set_size: 512
    summaries: ["log_posterior", "l2_norm"]
    r_hat_threshold: 1.05  # Not used for multimodal assessment
    ess_threshold: 50  # Used for within-mode mixing (threshold/4 = 12.5)
    track_min_ess: true  # Track minimum ESS across all chains and metrics

output:
  save_dir: "runs/mrpc_roberta_lora_sgld"
  save_samples: true
  save_traces: true
