# Configuration for MRPC RoBERTa LoRA SAM-SGLD Rank-1 Experiment
# Based on experiment outline in sgld_lora_experiment.md

experiment:
  name: "mrpc_roberta_lora_samsgld_rank1"
  description: "SAM-SGLD Rank-1 for Bayesian LoRA on MRPC dataset"
  
model:
  backbone: "roberta-base"
  max_sequence_length: 256
  lora:
    inject_into: ["query", "key", "value", "attention.output.dense"]  # Only attention modules
    rank: 8  # Increased for better expressiveness
    alpha: 16  # Increased proportionally with rank
    dropout: 0.1

data:
  dataset: "mrpc"
  batch_size: 32  # Optimized for best convergence and GPU utilization
  gradient_accumulation_steps: 1  # No longer needed with larger batch size
  max_epochs: 20

training:
  map_lora:
    optimizer: "sgd"  # Changed to SGD for apples-to-apples comparison with SGLD
    learning_rate: 3e-3  # Optimal LR for SGD (tested and found to be best)
    weight_decay: 0.01
    momentum: 0.5  # Optimal momentum for SGD (tested and found to be best)
    scheduler: "none"  # Disable scheduler to avoid LR decay
    warmup_ratio: 0.0  # Disable warmup
  
  samsgld_rank1_lora:
    learning_rate: 1e-4  # Final adjustment to control parameter drift
    temperature: 2.0  # Match working SGLD temperature for better exploration
    prior_std: 10.0  # Further increased to reduce prior strength and improve balance
    step_size_schedule:
      initial: 1e-4  # Match final reduced learning rate
      decay_rate: 0.3  # Conservative decay for better convergence
      decay_steps: 3000  # Longer decay schedule for stability
    gradient_clip_norm: 5.0  # Match working SGLD gradient clipping
    noise_scale: 0.5  # Increased to improve noise/gradient balance for better ESS
    # SAM-SGLD specific parameters
    rho: 0.05  # SAM perturbation radius (standard SAM literature value)
    lambd: 0.00000001  # SAM regularization (1e-8)
    sigma_dir: 0.5  # Increased for better rank-1 directional exploration
    chains: 4  # Multiple chains for R-hat computation
    burn_in_steps: 8000  # Sufficient burn-in for convergence
    sampling_steps: 3000  # 60 samples per chain * 50 thinning = 3000 steps
    thinning: 50  # Good thinning for sample independence
    samples_to_retain: 240  # Match total samples (4 chains * 60 samples per chain)

evaluation:
  metrics: ["accuracy", "nll", "ece"]
  mcmc_diagnostics:
    probe_set_size: 512
    summaries: ["log_posterior", "l2_norm"]
    r_hat_threshold: 1.05  # Not used for multimodal assessment
    ess_threshold: 50  # Used for within-mode mixing (threshold/4 = 12.5)
    track_min_ess: true  # Track minimum ESS across all chains and metrics

output:
  save_dir: "runs/mrpc_roberta_lora_samsgld_rank1"
  save_samples: true
  save_traces: true
