# Configuration for MRPC RoBERTa LoRA SGLD Experiment
# Based on experiment outline in sgld_lora_experiment.md

experiment:
  name: "mrpc_roberta_lora_sgld"
  description: "SGLD for Bayesian LoRA on MRPC dataset"
  
model:
  backbone: "roberta-base"
  max_sequence_length: 256
  lora:
    inject_into: ["query", "key", "value", "attention.output.dense"]  # Only attention modules
    rank: 8  # Increased for better expressiveness
    alpha: 16  # Increased proportionally with rank
    dropout: 0.1

data:
  dataset: "mrpc"
  batch_size: 32  # Optimized for best convergence and GPU utilization
  gradient_accumulation_steps: 1  # No longer needed with larger batch size
  max_epochs: 20

training:
  map_lora:
    optimizer: "sgd"  # Changed to SGD for apples-to-apples comparison with SGLD
    learning_rate: 1e-3  # Higher LR for SGD (typically needs 10x higher than AdamW)
    weight_decay: 0.01
    momentum: 0.9  # SGD momentum
    scheduler: "linear"
    warmup_ratio: 0.1
  
  sgld_lora:
    learning_rate: 1e-4  # Smaller step size for stable SGLD sampling
    temperature: 1.0
    prior_std: 0.01  # Very strong prior to balance likelihood
    step_size_schedule:
      initial: 1e-4  # Smaller step size for stable SGLD sampling
      decay_rate: 0.3  # Conservative decay for better convergence
      decay_steps: 3000  # Longer decay schedule
    gradient_clip_norm: 1.0
    chains: 4  # Restored for R-hat computation
    burn_in_steps: 8000  # Longer burn-in for better convergence
    sampling_steps: 12000  # More samples for better ESS
    thinning: 50  # Higher thinning for more independent samples
    samples_to_retain: 200

evaluation:
  metrics: ["accuracy", "nll", "ece"]
  mcmc_diagnostics:
    probe_set_size: 512
    summaries: ["log_posterior", "l2_norm"]
    r_hat_threshold: 1.05
    ess_threshold: 200

output:
  save_dir: "runs/mrpc_roberta_lora_sgld"
  save_samples: true
  save_traces: true
