# Configuration for MRPC RoBERTa LoRA SAM-SGLD Rank-1 Experiment
# Based on experiment outline in sgld_lora_experiment.md

experiment:
  name: "mrpc_roberta_lora_samsgld_rank1"
  description: "SAM-SGLD Rank-1 for Bayesian LoRA on MRPC dataset"
  
model:
  backbone: "roberta-base"
  max_sequence_length: 256
  lora:
    inject_into: ["query", "key", "value", "attention.output.dense"]  # Only attention modules
    rank: 8  # Increased for better expressiveness
    alpha: 16  # Increased proportionally with rank
    dropout: 0.1

data:
  dataset: "mrpc"
  batch_size: 32  # Optimized for best convergence and GPU utilization
  gradient_accumulation_steps: 1  # No longer needed with larger batch size
  max_epochs: 20  # Full training for proper MAP model

training:
  map_lora:
    optimizer: "sgd"  # Changed to SGD for apples-to-apples comparison with SGLD
    learning_rate: 3e-3  # Optimal LR for SGD (tested and found to be best)
    weight_decay: 0.01
    momentum: 0.5  # Optimal momentum for SGD (tested and found to be best)
    scheduler: "none"  # Disable scheduler to avoid LR decay
    warmup_ratio: 0.0  # Disable warmup
  
  samsgld_rank1_lora:
    learning_rate: 5e-4
    temperature: 2.0  # Increased to balance step/noise ratio (was 1.5, too low)
    prior_std: 17.0  # Will be properly balanced using correct ratio calculation
    step_size_schedule:
      initial: 5e-4
      decay_rate: 0.3  # Conservative decay for better convergence
      decay_steps: 3000  # Longer decay schedule for stability
    gradient_clip_norm: 5.0  # Match SGLD clipping (was 1.0)
    noise_scale: 0.000002  # Increased to restore MCMC exploration
    # SAM-SGLD specific parameters
    rho: 0.05  # SAM perturbation radius (standard value)
    lambd: 0.00000001  # SAM regularization (1e-8)
    sigma_dir: 0.204  # Balanced for 20% rank-1 noise contribution
    chains: 1  # Multiple chains for R-hat computation
    burn_in_steps: 8000  # Full burn-in for proper convergence
    sampling_steps: 3000  # Full sampling for proper MCMC diagnostics
    thinning: 50  # Standard thinning for sample independence
    samples_to_retain: 240  # 4 chain * 240 samples = 240 total samples

evaluation:
  metrics: ["accuracy", "nll", "ece"]
  mcmc_diagnostics:
    probe_set_size: 512
    summaries: ["log_posterior", "l2_norm"]
    r_hat_threshold: 1.05  # Not used for multimodal assessment
    ess_threshold: 50  # Used for within-mode mixing (threshold/4 = 12.5)
    track_min_ess: true  # Track minimum ESS across all chains and metrics

output:
  save_dir: "runs/mrpc_roberta_lora_samsgld_rank1"
  save_samples: true
  save_traces: true
