# Configuration for MRPC RoBERTa LoRA SGLD Experiment
# Based on experiment outline in sgld_lora_experiment.md

experiment:
  name: "mrpc_roberta_lora_sgld"
  description: "SGLD for Bayesian LoRA on MRPC dataset"
  
model:
  backbone: "roberta-base"
  max_sequence_length: 32  # Ultra-reduced for GPU memory constraints
  lora:
    inject_into: ["query", "key", "value", "attention.output.dense"]  # Only attention modules
    rank: 2  # Ultra-reduced rank for memory efficiency
    alpha: 4  # Reduced alpha proportionally
    dropout: 0.05

data:
  dataset: "mrpc"
  batch_size: 4  # Ultra-reduced for GPU memory constraints
  gradient_accumulation_steps: 8  # Maintain effective batch size of 32
  max_epochs: 20

training:
  map_lora:
    optimizer: "adamw"
    learning_rate: 5e-5
    weight_decay: 0.01
    beta1: 0.9
    beta2: 0.999
    scheduler: "linear"
    warmup_ratio: 0.1
  
  sgld_lora:
    learning_rate: 1e-4
    temperature: 1.0
    prior_std: 0.1
    step_size_schedule:
      initial: 1e-4
      decay_rate: 0.6
      decay_steps: 1000
    gradient_clip_norm: 1.0
    chains: 3  # Restored for R-hat computation
    burn_in_steps: 500  # Keep reduced for faster execution
    sampling_steps: 2000  # Keep reduced for faster execution
    thinning: 10  # Reduced thinning for more samples
    samples_to_retain: 200

evaluation:
  metrics: ["accuracy", "nll", "ece"]
  mcmc_diagnostics:
    probe_set_size: 512
    summaries: ["log_posterior", "l2_norm"]
    r_hat_threshold: 1.05
    ess_threshold: 200

output:
  save_dir: "runs/mrpc_roberta_lora_sgld"
  save_samples: true
  save_traces: true
