# Configuration for MRPC RoBERTa LoRA SAM-SGLD Rank-1 Experiment
# Based on experiment outline in sgld_lora_experiment.md

experiment:
  name: "mrpc_roberta_lora_samsgld_rank1"
  description: "SAM-SGLD Rank-1 for Bayesian LoRA on MRPC dataset"
  
model:
  backbone: "roberta-base"
  max_sequence_length: 256
  lora:
    inject_into: ["query", "key", "value", "attention.output.dense"]  # Only attention modules
    rank: 8  # Increased for better expressiveness
    alpha: 16  # Increased proportionally with rank
    dropout: 0.1

data:
  dataset: "mrpc"
  batch_size: 32  # Optimized for best convergence and GPU utilization
  gradient_accumulation_steps: 1  # No longer needed with larger batch size
  max_epochs: 15  # Full training for proper MAP model

training:
  map_lora:
    optimizer: "adam"  # JUSTIFIED: Adam achieves 82% vs SGD's 68% MAP accuracy
    learning_rate: 2e-4  # Standard Adam learning rate
    weight_decay: 0.01
    beta1: 0.9  # Adam momentum decay
    beta2: 0.999  # Adam squared gradient decay
    eps: 1e-8  # Adam epsilon for numerical stability
    scheduler: "none"  # Disable scheduler to avoid LR decay
    warmup_ratio: 0.0  # Disable warmup
  
  samsgld_rank1_lora:
    learning_rate: 5e-4
    temperature: 2.0  # Increased to balance step/noise ratio (was 1.5, too low)
    prior_std: 17.0  # Will be properly balanced using correct ratio calculation
    step_size_schedule:
      initial: 0.002  # JUSTIFIED: Drift/noise ratio 0.115 is too low, need smaller step size
      decay_rate: 0.3  # Conservative decay for better convergence
      decay_steps: 1000  # Reduced for quick testing
    gradient_clip_norm: 5.0  # Match SGLD clipping (was 1.0)
    noise_scale: 0.00005  # JUSTIFIED: Reduce noise to improve drift/noise ratio from 0.115
    # SAM-SGLD specific parameters
    rho: 0.05  # Slightly reduced to prevent excessive SAM perturbation
    lambd: 0.00000001  # SAM regularization (1e-8)
    sigma_dir: 2.0  # JUSTIFIED: Current 1.3% contribution too low, increase from 1.0 to 1.5 for higher contribution
    chains: 1  # Single chain for testing (R-hat will be 1.0)
    burn_in_steps: 1500  # QUICK TEST: Reduced from 8000 for rapid diagnostics
    sampling_steps: 500  # QUICK TEST: Reduced from 3000 for rapid diagnostics
    thinning: 10  # QUICK TEST: Reduced from 50 for more samples
    samples_to_retain: 50  # 1 chain * 50 samples = 50 total samples

evaluation:
  metrics: ["accuracy", "nll", "ece"]
  mcmc_diagnostics:
    probe_set_size: 512
    summaries: ["log_posterior", "l2_norm"]
    r_hat_threshold: 1.05  # Not used for multimodal assessment
    ess_threshold: 50  # Used for within-mode mixing (threshold/4 = 12.5)
    track_min_ess: true  # Track minimum ESS across all chains and metrics

output:
  save_dir: "runs/mrpc_roberta_lora_samsgld_rank1"
  save_samples: true
  save_traces: true
